// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	SayRequest
	Recipient
	SayReply
	MessageWithBytes
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SayRequest struct {
	SayWhat   string     `protobuf:"bytes,1,opt,name=sayWhat" json:"sayWhat,omitempty"`
	Recipient *Recipient `protobuf:"bytes,2,opt,name=recipient" json:"recipient,omitempty"`
}

func (m *SayRequest) Reset()                    { *m = SayRequest{} }
func (m *SayRequest) String() string            { return proto.CompactTextString(m) }
func (*SayRequest) ProtoMessage()               {}
func (*SayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayRequest) GetSayWhat() string {
	if m != nil {
		return m.SayWhat
	}
	return ""
}

func (m *SayRequest) GetRecipient() *Recipient {
	if m != nil {
		return m.Recipient
	}
	return nil
}

type Recipient struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NumberOfTimes int32  `protobuf:"varint,2,opt,name=numberOfTimes" json:"numberOfTimes,omitempty"`
}

func (m *Recipient) Reset()                    { *m = Recipient{} }
func (m *Recipient) String() string            { return proto.CompactTextString(m) }
func (*Recipient) ProtoMessage()               {}
func (*Recipient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Recipient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipient) GetNumberOfTimes() int32 {
	if m != nil {
		return m.NumberOfTimes
	}
	return 0
}

type SayReply struct {
	SaidWhat string `protobuf:"bytes,1,opt,name=saidWhat" json:"saidWhat,omitempty"`
}

func (m *SayReply) Reset()                    { *m = SayReply{} }
func (m *SayReply) String() string            { return proto.CompactTextString(m) }
func (*SayReply) ProtoMessage()               {}
func (*SayReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SayReply) GetSaidWhat() string {
	if m != nil {
		return m.SaidWhat
	}
	return ""
}

type MessageWithBytes struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=Bytes,json=bytes,proto3" json:"Bytes,omitempty"`
}

func (m *MessageWithBytes) Reset()                    { *m = MessageWithBytes{} }
func (m *MessageWithBytes) String() string            { return proto.CompactTextString(m) }
func (*MessageWithBytes) ProtoMessage()               {}
func (*MessageWithBytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MessageWithBytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*SayRequest)(nil), "main.SayRequest")
	proto.RegisterType((*Recipient)(nil), "main.Recipient")
	proto.RegisterType((*SayReply)(nil), "main.SayReply")
	proto.RegisterType((*MessageWithBytes)(nil), "main.MessageWithBytes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ExampleService service

type ExampleServiceClient interface {
	SayHello(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayReply, error)
	SayHelloStream(ctx context.Context, opts ...grpc.CallOption) (ExampleService_SayHelloStreamClient, error)
	Bytes(ctx context.Context, in *MessageWithBytes, opts ...grpc.CallOption) (*MessageWithBytes, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) SayHello(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayReply, error) {
	out := new(SayReply)
	err := grpc.Invoke(ctx, "/main.ExampleService/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) SayHelloStream(ctx context.Context, opts ...grpc.CallOption) (ExampleService_SayHelloStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ExampleService_serviceDesc.Streams[0], c.cc, "/main.ExampleService/SayHelloStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServiceSayHelloStreamClient{stream}
	return x, nil
}

type ExampleService_SayHelloStreamClient interface {
	Send(*SayRequest) error
	Recv() (*SayReply, error)
	grpc.ClientStream
}

type exampleServiceSayHelloStreamClient struct {
	grpc.ClientStream
}

func (x *exampleServiceSayHelloStreamClient) Send(m *SayRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleServiceSayHelloStreamClient) Recv() (*SayReply, error) {
	m := new(SayReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleServiceClient) Bytes(ctx context.Context, in *MessageWithBytes, opts ...grpc.CallOption) (*MessageWithBytes, error) {
	out := new(MessageWithBytes)
	err := grpc.Invoke(ctx, "/main.ExampleService/Bytes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExampleService service

type ExampleServiceServer interface {
	SayHello(context.Context, *SayRequest) (*SayReply, error)
	SayHelloStream(ExampleService_SayHelloStreamServer) error
	Bytes(context.Context, *MessageWithBytes) (*MessageWithBytes, error)
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ExampleService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).SayHello(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_SayHelloStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServiceServer).SayHelloStream(&exampleServiceSayHelloStreamServer{stream})
}

type ExampleService_SayHelloStreamServer interface {
	Send(*SayReply) error
	Recv() (*SayRequest, error)
	grpc.ServerStream
}

type exampleServiceSayHelloStreamServer struct {
	grpc.ServerStream
}

func (x *exampleServiceSayHelloStreamServer) Send(m *SayReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleServiceSayHelloStreamServer) Recv() (*SayRequest, error) {
	m := new(SayRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ExampleService_Bytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWithBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Bytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ExampleService/Bytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Bytes(ctx, req.(*MessageWithBytes))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ExampleService_SayHello_Handler,
		},
		{
			MethodName: "Bytes",
			Handler:    _ExampleService_Bytes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloStream",
			Handler:       _ExampleService_SayHelloStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x97, 0xb9, 0xe9, 0x76, 0x75, 0xb5, 0x5c, 0x44, 0x4a, 0x9f, 0x46, 0x10, 0xe9, 0x8b,
	0x45, 0xe6, 0x8b, 0xbe, 0x0a, 0x03, 0x11, 0x44, 0x48, 0x95, 0x3d, 0xa7, 0xf3, 0xea, 0x02, 0x4d,
	0x5b, 0x9b, 0x4c, 0xec, 0x0f, 0xf3, 0xff, 0xc9, 0xd2, 0x75, 0x9b, 0x82, 0xe0, 0xdb, 0x3d, 0x5f,
	0x4f, 0x4f, 0x4e, 0x6e, 0x60, 0x44, 0x9f, 0x52, 0x97, 0x19, 0xc5, 0x65, 0x55, 0xd8, 0x02, 0x7b,
	0x5a, 0xaa, 0x9c, 0x3f, 0x03, 0x24, 0xb2, 0x16, 0xf4, 0xbe, 0x24, 0x63, 0x31, 0x80, 0x03, 0x23,
	0xeb, 0xd9, 0x42, 0xda, 0x80, 0x8d, 0x59, 0x34, 0x14, 0xad, 0xc4, 0x0b, 0x18, 0x56, 0x34, 0x57,
	0xa5, 0xa2, 0xdc, 0x06, 0xdd, 0x31, 0x8b, 0x0e, 0x27, 0xc7, 0xf1, 0x2a, 0x21, 0x16, 0x2d, 0x16,
	0x5b, 0x07, 0x9f, 0xc2, 0x70, 0xc3, 0x11, 0xa1, 0x97, 0x4b, 0x4d, 0xeb, 0x48, 0x37, 0xe3, 0x19,
	0x8c, 0xf2, 0xa5, 0x4e, 0xa9, 0x7a, 0x7c, 0x7d, 0x52, 0x9a, 0x8c, 0xcb, 0xec, 0x8b, 0x9f, 0x90,
	0x9f, 0xc3, 0xc0, 0xb5, 0x2b, 0xb3, 0x1a, 0x43, 0x18, 0x18, 0xa9, 0x5e, 0x76, 0xca, 0x6d, 0x34,
	0x8f, 0xc1, 0x7f, 0x20, 0x63, 0xe4, 0x1b, 0xcd, 0x94, 0x5d, 0xdc, 0xd6, 0x96, 0x0c, 0x9e, 0x40,
	0xdf, 0x0d, 0xce, 0x7c, 0x24, 0xfa, 0xe9, 0x4a, 0xdc, 0xf7, 0x06, 0x5d, 0x7f, 0x6f, 0xf2, 0xc5,
	0xc0, 0x9b, 0x36, 0xdb, 0x48, 0xa8, 0xfa, 0x50, 0x73, 0xc2, 0xd8, 0x1d, 0x75, 0x47, 0x59, 0x56,
	0xa0, 0xdf, 0xdc, 0x6c, 0xbb, 0x98, 0xd0, 0xdb, 0x21, 0x65, 0x56, 0xf3, 0x0e, 0x5e, 0x83, 0xd7,
	0xfa, 0x13, 0x5b, 0x91, 0xd4, 0xff, 0xf9, 0x2b, 0x62, 0x97, 0x0c, 0x6f, 0xd6, 0xc5, 0xf0, 0xb4,
	0xf9, 0xfc, 0xbb, 0x79, 0xf8, 0x07, 0xe7, 0x9d, 0x74, 0xdf, 0x3d, 0xdd, 0xd5, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0x30, 0xe0, 0xb7, 0xcb, 0x01, 0x00, 0x00,
}
